### ISSUE TITLE
Create CI with Travis

### ISSUE THREAD

**Issue by robnn** [javas-csavok/outlay#1]

**Comment by robnn** [comment]
After a lot of experimenting with the .travis.yml, the commit 32fe0c3 makes it work, at last. Configured the .travis.yml to only build for debug because we dont need signed apk-s. I've created a google-services.json, wich is needed by the firebase components. @stahopeti summoned to review and close.

**Comment by stahopeti** [comment]
Very nice work, I declare the issue closed.

**Comment by micskeiz** [comment]
OK
