### ISSUE TITLE
SonarQube static analysis

### ISSUE THREAD

**Issue by robnn** [javas-csavok/outlay#2]

**Comment by robnn** [comment]
Commented out the android build specific things int the .travis.yml to speed up the sonar build in 687406a74a53dea75f1a8dab20c865b9e6fad4d5 , so for a full build, has to remove the hashmarks.

**Comment by robnn** [comment]
fixed vulnerability errors in ResurceUtils.java in 06830331998ce59e05560f3ddbcabc8a87b7b43c and 03f937903cfd22df9cdfaa3447a0c25786817841

**Comment by Razgore** [comment]
Refactored the code a littlebit, to get a higher Reliabilty rating in SonarQube.

**Comment by robnn** [comment]
on the sonar cube, the code coverage is 0% so it fails the quality gate, but since this is a static analysis, this is not a problem. Summon @stahopeti  to review and close the issue.

**Comment by stahopeti** [comment]
0% code coverage is not an issue for now, we will take care of it in the next part of the development. Nice work. Issue closed.

**Comment by micskeiz** [comment]
OK
