### ISSUE TITLE
Create DeviceUtils Test

### ISSUE THREAD

**Issue by robnn** [javas-csavok/outlay#5]

**Comment by robnn** [comment]
HideKeyboard method tests with branch: b0716128d1d5896e0658c3b2c57175d8bec6115a

**Comment by robnn** [comment]
ActionBarheight true branch cannot be tested, because the creation of a TypedValue object, witch is not injected in the method. d8ff255891306a0b1e9f47f47d324598398d15a4

**Comment by Razgore** [comment]
Solved by: 6bbf3b4e1139230bf1f4ff3fde2409d82a539106
getScreenSize() cannot be tested. The rest works fine.

**Comment by stahopeti** [comment]
Thanks, nice work!
